### PR TITLE
Add negated orderHistory parameters and deleteUsers method

### PR DESCRIPTION
**Pull request by RoseannaM**
New method created for the deletion of one or many users:
[gocommerce #149](https://github.com/netlify/gocommerce/pull/149)
Allowed negated parameters for the order history method:
[gocommerce #152](https://github.com/netlify/gocommerce/pull/152)

Closes https://github.com/netlify/gocommerce-js/issues/21
Closes https://github.com/netlify/gocommerce-js/issues/20

### CODE REVIEW

**Review by bcomnes — CHANGES_REQUESTED** [review]
Lets make the arguments into options objects instead, in a way that doesn't break the existing API.

**Comment by bcomnes** [comment]
I'll go ahead and make the tweak.

**Comment by bcomnes** [comment]
Oh wait we can't do that, parames is already an object.

**Review by bcomnes — APPROVED** [review]

**Comment by bcomnes** [comment]
Ok, instead of adding a single additional argument, I wrapped them in an options object so we have room to grow.

**Comment by RoseannaM** [comment]
Awesome, thanks!

**Pull request merged**
