### PR TITLE
Fix calculation to apply taxes after discount

### LINKED ISSUE #16: Tax calculation disregards discounts [CRITICAL]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
The total tax stays the same even if a discount code is applied
(while it actually should be based to the final price, including the
discount)

**- What is the expected behavior?**
Tax calculation should be based to the final price, including the
discount

### PR DESCRIPTION
**Pull request by mraerino**
*Fixes #16*

This PR replicates https://github.com/netlify/gocommerce/pull/155 for the JS lib.
The tests have been synced manually to verify similar behavior.

### CODE REVIEW

**Comment by mraerino** [comment]
@bcomnes this has been updated to do the same as what has been refined in my GoCommerce PR. Description about tests etc still applies.
Ready for review 😊

**Comment by bcomnes** [comment]
Triaged this today.  Will review soon.

**Review by bcomnes — APPROVED** [review]
LGTM

@mraerino versionwise, would this be a breaking change?  Also, do we need to enforce any kind of version requirements between the client and server?

**Comment by mraerino** [comment]
@bcomnes
this change is not connected to any api code. it is only needed for a price preview before issuing the order.

the only thing that is changed and not added in this fix is the behavior of the tax amount field. but since the behavior was wrong before (considering any taxation system in US or Europe) it should rather be classified as a bug fix than a breaking change.
If you want to make it a minor version bump then do it because of the added field `net_total`.

**Comment by bcomnes** [comment]
OK sounds good.

**Comment by bcomnes** [comment]
[🎉`+ gocommerce-js@4.2.0`🎉](https://github.com/netlify/gocommerce-js/releases/tag/v4.2.0)

**Pull request merged**
